#include "cairoffi.h"
#define TPTR(a,t) (ART(in->a.hdr) != 7) || in->a.hdr.len != 2 || ((long*)in->a.arr)[1] != t ||
#define LONG(a) (ART(in->a.hdr) != 14) || in->a.hdr.len != 1 ||
#define DOUBLE(a) (ART(in->a.hdr) != 15) || in->a.hdr.len != 1 ||
#define INT(a) (in->typ##a) != 13 ||
#define STRING(a) (ART(in->a.hdr) != 9) ||

//cairo_version_sig* chk_cairo_version_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_version_sig* in = (cairo_version_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
//cairo_version_string_sig* chk_cairo_version_string_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_version_string_sig* in = (cairo_version_string_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
//cairo_create_sig* chk_cairo_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_create_sig* in = (cairo_create_sig*)(x+1); if( in->lst.len != 1 || TPTR(target,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_reference_sig* chk_cairo_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_reference_sig* in = (cairo_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
//cairo_destroy_sig* chk_cairo_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_destroy_sig* in = (cairo_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_reference_count_sig* chk_cairo_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_reference_count_sig* in = (cairo_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_user_data_sig* chk_cairo_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_user_data_sig* in = (cairo_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_set_user_data_sig* chk_cairo_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_user_data_sig* in = (cairo_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
//cairo_save_sig* chk_cairo_save_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_save_sig* in = (cairo_save_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
//cairo_restore_sig* chk_cairo_restore_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_restore_sig* in = (cairo_restore_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_push_group_sig* chk_cairo_push_group_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_push_group_sig* in = (cairo_push_group_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_push_group_with_content_sig* chk_cairo_push_group_with_content_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_push_group_with_content_sig* in = (cairo_push_group_with_content_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(content) 0) { return 0; }; return in; }
cairo_pop_group_sig* chk_cairo_pop_group_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pop_group_sig* in = (cairo_pop_group_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_pop_group_to_source_sig* chk_cairo_pop_group_to_source_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pop_group_to_source_sig* in = (cairo_pop_group_to_source_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_set_operator_sig* chk_cairo_set_operator_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_operator_sig* in = (cairo_set_operator_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(op) 0) { return 0; }; return in; }
cairo_set_source_sig* chk_cairo_set_source_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_source_sig* in = (cairo_set_source_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(source,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_set_source_rgb_sig* chk_cairo_set_source_rgb_sig(S x){ if (x[0] != VER || x[1] != 1) return 0;
 cairo_set_source_rgb_sig* in = (cairo_set_source_rgb_sig*)(x+1);
 if( in->lst.len != 4 ||
	 TPTR(cr,KFFI_CAIRO_T)
	 DOUBLE(red)
	 DOUBLE(green)
	 DOUBLE(blue) 0) { return 0;
 };
 return in;
 }
cairo_set_source_rgba_sig* chk_cairo_set_source_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_source_rgba_sig* in = (cairo_set_source_rgba_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_set_source_surface_sig* chk_cairo_set_source_surface_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_source_surface_sig* in = (cairo_set_source_surface_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_set_tolerance_sig* chk_cairo_set_tolerance_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_tolerance_sig* in = (cairo_set_tolerance_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(tolerance) 0) { return 0; }; return in; }
cairo_set_antialias_sig* chk_cairo_set_antialias_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_antialias_sig* in = (cairo_set_antialias_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(antialias) 0) { return 0; }; return in; }
cairo_set_fill_rule_sig* chk_cairo_set_fill_rule_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_fill_rule_sig* in = (cairo_set_fill_rule_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(fill_rule) 0) { return 0; }; return in; }
cairo_set_line_width_sig* chk_cairo_set_line_width_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_line_width_sig* in = (cairo_set_line_width_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(width) 0) { return 0; }; return in; }
cairo_set_hairline_sig* chk_cairo_set_hairline_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_hairline_sig* in = (cairo_set_hairline_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_set_line_cap_sig* chk_cairo_set_line_cap_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_line_cap_sig* in = (cairo_set_line_cap_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(line_cap) 0) { return 0; }; return in; }
cairo_set_line_join_sig* chk_cairo_set_line_join_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_line_join_sig* in = (cairo_set_line_join_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) INT(line_join) 0) { return 0; }; return in; }
cairo_set_dash_sig* chk_cairo_set_dash_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_dash_sig* in = (cairo_set_dash_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dashes) INT(num_dashes)

																																				  DOUBLE(offset) 0) { return 0; }; return in; }
cairo_set_miter_limit_sig* chk_cairo_set_miter_limit_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_miter_limit_sig* in = (cairo_set_miter_limit_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(limit) 0) { return 0; }; return in; }
cairo_translate_sig* chk_cairo_translate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_translate_sig* in = (cairo_translate_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(tx) DOUBLE(ty) 0) { return 0; }; return in; }
cairo_scale_sig* chk_cairo_scale_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scale_sig* in = (cairo_scale_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(sx) DOUBLE(sy) 0) { return 0; }; return in; }
cairo_rotate_sig* chk_cairo_rotate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rotate_sig* in = (cairo_rotate_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(angle) 0) { return 0; }; return in; }
cairo_transform_sig* chk_cairo_transform_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_transform_sig* in = (cairo_transform_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_set_matrix_sig* chk_cairo_set_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_matrix_sig* in = (cairo_set_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_identity_matrix_sig* chk_cairo_identity_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_identity_matrix_sig* in = (cairo_identity_matrix_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_user_to_device_sig* chk_cairo_user_to_device_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_to_device_sig* in = (cairo_user_to_device_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_user_to_device_distance_sig* chk_cairo_user_to_device_distance_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_to_device_distance_sig* in = (cairo_user_to_device_distance_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dx) DOUBLE(dy) 0) { return 0; }; return in; }
cairo_device_to_user_sig* chk_cairo_device_to_user_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_to_user_sig* in = (cairo_device_to_user_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_device_to_user_distance_sig* chk_cairo_device_to_user_distance_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_to_user_distance_sig* in = (cairo_device_to_user_distance_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dx) DOUBLE(dy) 0) { return 0; }; return in; }
//cairo_new_path_sig* chk_cairo_new_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_new_path_sig* in = (cairo_new_path_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_move_to_sig* chk_cairo_move_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_move_to_sig* in = (cairo_move_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_new_sub_path_sig* chk_cairo_new_sub_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_new_sub_path_sig* in = (cairo_new_sub_path_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_line_to_sig* chk_cairo_line_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_line_to_sig* in = (cairo_line_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_curve_to_sig* chk_cairo_curve_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_curve_to_sig* in = (cairo_curve_to_sig*)(x+1); if( in->lst.len != 7 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) DOUBLE(x3) DOUBLE(y3) 0) { return 0; }; return in; }
cairo_arc_sig* chk_cairo_arc_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_arc_sig* in = (cairo_arc_sig*)(x+1); if( in->lst.len != 6 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(xc) DOUBLE(yc) DOUBLE(radius) DOUBLE(angle1) DOUBLE(angle2) 0) { return 0; }; return in; }
cairo_arc_negative_sig* chk_cairo_arc_negative_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_arc_negative_sig* in = (cairo_arc_negative_sig*)(x+1); if( in->lst.len != 6 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(xc) DOUBLE(yc) DOUBLE(radius) DOUBLE(angle1) DOUBLE(angle2) 0) { return 0; }; return in; }
cairo_rel_move_to_sig* chk_cairo_rel_move_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rel_move_to_sig* in = (cairo_rel_move_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dx) DOUBLE(dy) 0) { return 0; }; return in; }
cairo_rel_line_to_sig* chk_cairo_rel_line_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rel_line_to_sig* in = (cairo_rel_line_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dx) DOUBLE(dy) 0) { return 0; }; return in; }
cairo_rel_curve_to_sig* chk_cairo_rel_curve_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rel_curve_to_sig* in = (cairo_rel_curve_to_sig*)(x+1); if( in->lst.len != 7 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dx1) DOUBLE(dy1) DOUBLE(dx2) DOUBLE(dy2) DOUBLE(dx3) DOUBLE(dy3) 0) { return 0; }; return in; }
cairo_rectangle_sig* chk_cairo_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rectangle_sig* in = (cairo_rectangle_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) DOUBLE(width) DOUBLE(height) 0) { return 0; }; return in; }
//cairo_close_path_sig* chk_cairo_close_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_close_path_sig* in = (cairo_close_path_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_path_extents_sig* chk_cairo_path_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_path_extents_sig* in = (cairo_path_extents_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) 0) { return 0; }; return in; }
cairo_paint_sig* chk_cairo_paint_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_paint_sig* in = (cairo_paint_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_paint_with_alpha_sig* chk_cairo_paint_with_alpha_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_paint_with_alpha_sig* in = (cairo_paint_with_alpha_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_mask_sig* chk_cairo_mask_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mask_sig* in = (cairo_mask_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_mask_surface_sig* chk_cairo_mask_surface_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mask_surface_sig* in = (cairo_mask_surface_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(surface_x) DOUBLE(surface_y) 0) { return 0; }; return in; }
//cairo_stroke_sig* chk_cairo_stroke_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_stroke_sig* in = (cairo_stroke_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_stroke_preserve_sig* chk_cairo_stroke_preserve_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_stroke_preserve_sig* in = (cairo_stroke_preserve_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
//cairo_fill_sig* chk_cairo_fill_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_fill_sig* in = (cairo_fill_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_fill_preserve_sig* chk_cairo_fill_preserve_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_fill_preserve_sig* in = (cairo_fill_preserve_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_copy_page_sig* chk_cairo_copy_page_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_copy_page_sig* in = (cairo_copy_page_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_show_page_sig* chk_cairo_show_page_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_show_page_sig* in = (cairo_show_page_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_in_stroke_sig* chk_cairo_in_stroke_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_in_stroke_sig* in = (cairo_in_stroke_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_in_fill_sig* chk_cairo_in_fill_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_in_fill_sig* in = (cairo_in_fill_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_in_clip_sig* chk_cairo_in_clip_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_in_clip_sig* in = (cairo_in_clip_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_stroke_extents_sig* chk_cairo_stroke_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_stroke_extents_sig* in = (cairo_stroke_extents_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) 0) { return 0; }; return in; }
cairo_fill_extents_sig* chk_cairo_fill_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_fill_extents_sig* in = (cairo_fill_extents_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) 0) { return 0; }; return in; }
//cairo_reset_clip_sig* chk_cairo_reset_clip_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_reset_clip_sig* in = (cairo_reset_clip_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_clip_sig* chk_cairo_clip_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_clip_sig* in = (cairo_clip_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_clip_preserve_sig* chk_cairo_clip_preserve_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_clip_preserve_sig* in = (cairo_clip_preserve_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_clip_extents_sig* chk_cairo_clip_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_clip_extents_sig* in = (cairo_clip_extents_sig*)(x+1); if( in->lst.len != 5 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) 0) { return 0; }; return in; }
cairo_copy_clip_rectangle_list_sig* chk_cairo_copy_clip_rectangle_list_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_copy_clip_rectangle_list_sig* in = (cairo_copy_clip_rectangle_list_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_rectangle_list_destroy_sig* chk_cairo_rectangle_list_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_rectangle_list_destroy_sig* in = (cairo_rectangle_list_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(rectangle_list,KFFI_CAIRO_RECTANGLE_LIST_T) 0) { return 0; }; return in; }
cairo_tag_begin_sig* chk_cairo_tag_begin_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_tag_begin_sig* in = (cairo_tag_begin_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) STRING(tag_name) STRING(attributes) 0) { return 0; }; return in; }
cairo_tag_end_sig* chk_cairo_tag_end_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_tag_end_sig* in = (cairo_tag_end_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T)  STRING(tag_name) 0) { return 0; }; return in; }
cairo_glyph_allocate_sig* chk_cairo_glyph_allocate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_glyph_allocate_sig* in = (cairo_glyph_allocate_sig*)(x+1); if( in->lst.len != 1 || INT(num_glyphs) 0) { return 0; }; return in; }
cairo_glyph_free_sig* chk_cairo_glyph_free_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_glyph_free_sig* in = (cairo_glyph_free_sig*)(x+1); if( in->lst.len != 1 || TPTR(glyphs,KFFI_CAIRO_GLYPH_T) 0) { return 0; }; return in; }
cairo_text_cluster_allocate_sig* chk_cairo_text_cluster_allocate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_text_cluster_allocate_sig* in = (cairo_text_cluster_allocate_sig*)(x+1); if( in->lst.len != 1 || INT(num_clusters) 0) { return 0; }; return in; }
cairo_text_cluster_free_sig* chk_cairo_text_cluster_free_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_text_cluster_free_sig* in = (cairo_text_cluster_free_sig*)(x+1); if( in->lst.len != 1 || TPTR(clusters,KFFI_CAIRO_TEXT_CLUSTER_T) 0) { return 0; }; return in; }
//cairo_font_options_create_sig* chk_cairo_font_options_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_create_sig* in = (cairo_font_options_create_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
cairo_font_options_copy_sig* chk_cairo_font_options_copy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_copy_sig* in = (cairo_font_options_copy_sig*)(x+1); if( in->lst.len != 1 || TPTR(original,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_destroy_sig* chk_cairo_font_options_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_destroy_sig* in = (cairo_font_options_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_status_sig* chk_cairo_font_options_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_status_sig* in = (cairo_font_options_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_merge_sig* chk_cairo_font_options_merge_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_merge_sig* in = (cairo_font_options_merge_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) TPTR(other,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_equal_sig* chk_cairo_font_options_equal_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_equal_sig* in = (cairo_font_options_equal_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) TPTR(other,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_hash_sig* chk_cairo_font_options_hash_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_hash_sig* in = (cairo_font_options_hash_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_set_antialias_sig* chk_cairo_font_options_set_antialias_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_set_antialias_sig* in = (cairo_font_options_set_antialias_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) INT(antialias) 0) { return 0; }; return in; }
cairo_font_options_get_antialias_sig* chk_cairo_font_options_get_antialias_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_get_antialias_sig* in = (cairo_font_options_get_antialias_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_set_subpixel_order_sig* chk_cairo_font_options_set_subpixel_order_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_set_subpixel_order_sig* in = (cairo_font_options_set_subpixel_order_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) INT(subpixel_order) 0) { return 0; }; return in; }
cairo_font_options_get_subpixel_order_sig* chk_cairo_font_options_get_subpixel_order_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_get_subpixel_order_sig* in = (cairo_font_options_get_subpixel_order_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_set_hint_style_sig* chk_cairo_font_options_set_hint_style_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_set_hint_style_sig* in = (cairo_font_options_set_hint_style_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) INT(hint_style) 0) { return 0; }; return in; }
cairo_font_options_get_hint_style_sig* chk_cairo_font_options_get_hint_style_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_get_hint_style_sig* in = (cairo_font_options_get_hint_style_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_set_hint_metrics_sig* chk_cairo_font_options_set_hint_metrics_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_set_hint_metrics_sig* in = (cairo_font_options_set_hint_metrics_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) INT(hint_metrics) 0) { return 0; }; return in; }
cairo_font_options_get_hint_metrics_sig* chk_cairo_font_options_get_hint_metrics_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_get_hint_metrics_sig* in = (cairo_font_options_get_hint_metrics_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_get_variations_sig* chk_cairo_font_options_get_variations_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_get_variations_sig* in = (cairo_font_options_get_variations_sig*)(x+1); if( in->lst.len != 1 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_font_options_set_variations_sig* chk_cairo_font_options_set_variations_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_options_set_variations_sig* in = (cairo_font_options_set_variations_sig*)(x+1); if( in->lst.len != 2 || TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) STRING(variations) 0) { return 0; }; return in; }
cairo_select_font_face_sig* chk_cairo_select_font_face_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_select_font_face_sig* in = (cairo_select_font_face_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) STRING(family) INT(slant) INT(weight) 0) { return 0; }; return in; }
cairo_set_font_size_sig* chk_cairo_set_font_size_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_font_size_sig* in = (cairo_set_font_size_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(size) 0) { return 0; }; return in; }
cairo_set_font_matrix_sig* chk_cairo_set_font_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_font_matrix_sig* in = (cairo_set_font_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_get_font_matrix_sig* chk_cairo_get_font_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_font_matrix_sig* in = (cairo_get_font_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_set_font_options_sig* chk_cairo_set_font_options_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_font_options_sig* in = (cairo_set_font_options_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_get_font_options_sig* chk_cairo_get_font_options_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_font_options_sig* in = (cairo_get_font_options_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_set_font_face_sig* chk_cairo_set_font_face_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_font_face_sig* in = (cairo_set_font_face_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_get_font_face_sig* chk_cairo_get_font_face_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_font_face_sig* in = (cairo_get_font_face_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_set_scaled_font_sig* chk_cairo_set_scaled_font_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_set_scaled_font_sig* in = (cairo_set_scaled_font_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_get_scaled_font_sig* chk_cairo_get_scaled_font_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_scaled_font_sig* in = (cairo_get_scaled_font_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_show_text_sig* chk_cairo_show_text_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_show_text_sig* in = (cairo_show_text_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) STRING(utf8) 0) { return 0; }; return in; }
cairo_show_glyphs_sig* chk_cairo_show_glyphs_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_show_glyphs_sig* in = (cairo_show_glyphs_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) TPTR(glyphs,KFFI_CAIRO_GLYPH_T) INT(num_glyphs) 0) { return 0; }; return in; }
cairo_show_text_glyphs_sig* chk_cairo_show_text_glyphs_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_show_text_glyphs_sig* in = (cairo_show_text_glyphs_sig*)(x+1); if( in->lst.len != 8 || TPTR(cr,KFFI_CAIRO_T) STRING(utf8) INT(utf8_len) TPTR(glyphs,KFFI_CAIRO_GLYPH_T) INT(num_glyphs) TPTR(clusters,KFFI_CAIRO_TEXT_CLUSTER_T) INT(num_clusters) INT(cluster_flags) 0) { return 0; }; return in; }
cairo_text_path_sig* chk_cairo_text_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_text_path_sig* in = (cairo_text_path_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) STRING(utf8) 0) { return 0; }; return in; }
cairo_glyph_path_sig* chk_cairo_glyph_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_glyph_path_sig* in = (cairo_glyph_path_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) TPTR(glyphs,KFFI_CAIRO_GLYPH_T) INT(num_glyphs) 0) { return 0; }; return in; }
cairo_text_extents_sig* chk_cairo_text_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_text_extents_sig* in = (cairo_text_extents_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) STRING(utf8) 0) { return 0; }; return in; }
cairo_glyph_extents_sig* chk_cairo_glyph_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_glyph_extents_sig* in = (cairo_glyph_extents_sig*)(x+1); if( in->lst.len != 4 || TPTR(cr,KFFI_CAIRO_T) TPTR(glyphs,KFFI_CAIRO_GLYPH_T) INT(num_glyphs) STRING(extents) 0) { return 0; }; return in; }
cairo_font_extents_sig* chk_cairo_font_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_extents_sig* in = (cairo_font_extents_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(extents,KFFI_CAIRO_FONT_EXTENTS_T) 0) { return 0; }; return in; }
cairo_font_face_reference_sig* chk_cairo_font_face_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_reference_sig* in = (cairo_font_face_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_font_face_destroy_sig* chk_cairo_font_face_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_destroy_sig* in = (cairo_font_face_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_font_face_get_reference_count_sig* chk_cairo_font_face_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_get_reference_count_sig* in = (cairo_font_face_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_font_face_status_sig* chk_cairo_font_face_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_status_sig* in = (cairo_font_face_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_font_face_get_type_sig* chk_cairo_font_face_get_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_get_type_sig* in = (cairo_font_face_get_type_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_font_face_get_user_data_sig* chk_cairo_font_face_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_get_user_data_sig* in = (cairo_font_face_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_font_face_set_user_data_sig* chk_cairo_font_face_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_font_face_set_user_data_sig* in = (cairo_font_face_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_scaled_font_create_sig* chk_cairo_scaled_font_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_create_sig* in = (cairo_scaled_font_create_sig*)(x+1); if( in->lst.len != 4 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) TPTR(font_matrix,KFFI_CAIRO_MATRIX_T) TPTR(ctm,KFFI_CAIRO_MATRIX_T) TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_scaled_font_reference_sig* chk_cairo_scaled_font_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_reference_sig* in = (cairo_scaled_font_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_destroy_sig* chk_cairo_scaled_font_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_destroy_sig* in = (cairo_scaled_font_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_reference_count_sig* chk_cairo_scaled_font_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_reference_count_sig* in = (cairo_scaled_font_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_status_sig* chk_cairo_scaled_font_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_status_sig* in = (cairo_scaled_font_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_type_sig* chk_cairo_scaled_font_get_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_type_sig* in = (cairo_scaled_font_get_type_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_user_data_sig* chk_cairo_scaled_font_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_user_data_sig* in = (cairo_scaled_font_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_scaled_font_set_user_data_sig* chk_cairo_scaled_font_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_set_user_data_sig* in = (cairo_scaled_font_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_scaled_font_extents_sig* chk_cairo_scaled_font_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_extents_sig* in = (cairo_scaled_font_extents_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(extents,KFFI_CAIRO_FONT_EXTENTS_T) 0) { return 0; }; return in; }
cairo_scaled_font_text_extents_sig* chk_cairo_scaled_font_text_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_text_extents_sig* in = (cairo_scaled_font_text_extents_sig*)(x+1); if( in->lst.len != 3 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) STRING(utf8) DOUBLE(extents) 0) { return 0; }; return in; }
cairo_scaled_font_glyph_extents_sig* chk_cairo_scaled_font_glyph_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_glyph_extents_sig* in = (cairo_scaled_font_glyph_extents_sig*)(x+1); if( in->lst.len != 4 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(glyphs,KFFI_CAIRO_GLYPH_T) INT(num_glyphs) STRING(extents) 0) { return 0; }; return in; }
cairo_scaled_font_text_to_glyphs_sig* chk_cairo_scaled_font_text_to_glyphs_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_text_to_glyphs_sig* in = (cairo_scaled_font_text_to_glyphs_sig*)(x+1); if( in->lst.len != 10 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) DOUBLE(x) DOUBLE(y) STRING(utf8) INT(utf8_len) 0) { return 0; }; return in; }
cairo_scaled_font_get_font_face_sig* chk_cairo_scaled_font_get_font_face_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_font_face_sig* in = (cairo_scaled_font_get_font_face_sig*)(x+1); if( in->lst.len != 1 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_font_matrix_sig* chk_cairo_scaled_font_get_font_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_font_matrix_sig* in = (cairo_scaled_font_get_font_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(font_matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_ctm_sig* chk_cairo_scaled_font_get_ctm_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_ctm_sig* in = (cairo_scaled_font_get_ctm_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(ctm,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_scale_matrix_sig* chk_cairo_scaled_font_get_scale_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_scale_matrix_sig* in = (cairo_scaled_font_get_scale_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(scale_matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_scaled_font_get_font_options_sig* chk_cairo_scaled_font_get_font_options_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_scaled_font_get_font_options_sig* in = (cairo_scaled_font_get_font_options_sig*)(x+1); if( in->lst.len != 2 || TPTR(scaled_font,KFFI_CAIRO_SCALED_FONT_T) TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
cairo_toy_font_face_create_sig* chk_cairo_toy_font_face_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_toy_font_face_create_sig* in = (cairo_toy_font_face_create_sig*)(x+1); if( in->lst.len != 3 || STRING(family) INT(slant) INT(weight) 0) { return 0; }; return in; }
cairo_toy_font_face_get_family_sig* chk_cairo_toy_font_face_get_family_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_toy_font_face_get_family_sig* in = (cairo_toy_font_face_get_family_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_toy_font_face_get_slant_sig* chk_cairo_toy_font_face_get_slant_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_toy_font_face_get_slant_sig* in = (cairo_toy_font_face_get_slant_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_toy_font_face_get_weight_sig* chk_cairo_toy_font_face_get_weight_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_toy_font_face_get_weight_sig* in = (cairo_toy_font_face_get_weight_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
//cairo_user_font_face_create_sig* chk_cairo_user_font_face_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_create_sig* in = (cairo_user_font_face_create_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
cairo_user_font_face_set_init_func_sig* chk_cairo_user_font_face_set_init_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_set_init_func_sig* in = (cairo_user_font_face_set_init_func_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_set_render_glyph_func_sig* chk_cairo_user_font_face_set_render_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_set_render_glyph_func_sig* in = (cairo_user_font_face_set_render_glyph_func_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_set_render_color_glyph_func_sig* chk_cairo_user_font_face_set_render_color_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_set_render_color_glyph_func_sig* in = (cairo_user_font_face_set_render_color_glyph_func_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_set_text_to_glyphs_func_sig* chk_cairo_user_font_face_set_text_to_glyphs_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_set_text_to_glyphs_func_sig* in = (cairo_user_font_face_set_text_to_glyphs_func_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_set_unicode_to_glyph_func_sig* chk_cairo_user_font_face_set_unicode_to_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_set_unicode_to_glyph_func_sig* in = (cairo_user_font_face_set_unicode_to_glyph_func_sig*)(x+1); if( in->lst.len != 2 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_get_init_func_sig* chk_cairo_user_font_face_get_init_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_get_init_func_sig* in = (cairo_user_font_face_get_init_func_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_get_render_glyph_func_sig* chk_cairo_user_font_face_get_render_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_get_render_glyph_func_sig* in = (cairo_user_font_face_get_render_glyph_func_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_get_render_color_glyph_func_sig* chk_cairo_user_font_face_get_render_color_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_get_render_color_glyph_func_sig* in = (cairo_user_font_face_get_render_color_glyph_func_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_get_text_to_glyphs_func_sig* chk_cairo_user_font_face_get_text_to_glyphs_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_get_text_to_glyphs_func_sig* in = (cairo_user_font_face_get_text_to_glyphs_func_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_user_font_face_get_unicode_to_glyph_func_sig* chk_cairo_user_font_face_get_unicode_to_glyph_func_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_user_font_face_get_unicode_to_glyph_func_sig* in = (cairo_user_font_face_get_unicode_to_glyph_func_sig*)(x+1); if( in->lst.len != 1 || TPTR(font_face,KFFI_CAIRO_FONT_FACE_T) 0) { return 0; }; return in; }
cairo_get_operator_sig* chk_cairo_get_operator_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_operator_sig* in = (cairo_get_operator_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_source_sig* chk_cairo_get_source_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_source_sig* in = (cairo_get_source_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_tolerance_sig* chk_cairo_get_tolerance_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_tolerance_sig* in = (cairo_get_tolerance_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_antialias_sig* chk_cairo_get_antialias_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_antialias_sig* in = (cairo_get_antialias_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_has_current_point_sig* chk_cairo_has_current_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_has_current_point_sig* in = (cairo_has_current_point_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_current_point_sig* chk_cairo_get_current_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_current_point_sig* in = (cairo_get_current_point_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_get_fill_rule_sig* chk_cairo_get_fill_rule_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_fill_rule_sig* in = (cairo_get_fill_rule_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_line_width_sig* chk_cairo_get_line_width_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_line_width_sig* in = (cairo_get_line_width_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_hairline_sig* chk_cairo_get_hairline_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_hairline_sig* in = (cairo_get_hairline_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_line_cap_sig* chk_cairo_get_line_cap_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_line_cap_sig* in = (cairo_get_line_cap_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_line_join_sig* chk_cairo_get_line_join_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_line_join_sig* in = (cairo_get_line_join_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_miter_limit_sig* chk_cairo_get_miter_limit_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_miter_limit_sig* in = (cairo_get_miter_limit_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_dash_count_sig* chk_cairo_get_dash_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_dash_count_sig* in = (cairo_get_dash_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_dash_sig* chk_cairo_get_dash_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_dash_sig* in = (cairo_get_dash_sig*)(x+1); if( in->lst.len != 3 || TPTR(cr,KFFI_CAIRO_T) DOUBLE(dashes) DOUBLE(offset) 0) { return 0; }; return in; }
cairo_get_matrix_sig* chk_cairo_get_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_matrix_sig* in = (cairo_get_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_get_target_sig* chk_cairo_get_target_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_target_sig* in = (cairo_get_target_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_get_group_target_sig* chk_cairo_get_group_target_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_get_group_target_sig* in = (cairo_get_group_target_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_copy_path_sig* chk_cairo_copy_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_copy_path_sig* in = (cairo_copy_path_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_copy_path_flat_sig* chk_cairo_copy_path_flat_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_copy_path_flat_sig* in = (cairo_copy_path_flat_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_append_path_sig* chk_cairo_append_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_append_path_sig* in = (cairo_append_path_sig*)(x+1); if( in->lst.len != 2 || TPTR(cr,KFFI_CAIRO_T) TPTR(path,KFFI_CAIRO_PATH_T) 0) { return 0; }; return in; }
cairo_path_destroy_sig* chk_cairo_path_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_path_destroy_sig* in = (cairo_path_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(path,KFFI_CAIRO_PATH_T) 0) { return 0; }; return in; }
//cairo_status_sig* chk_cairo_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_status_sig* in = (cairo_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(cr,KFFI_CAIRO_T) 0) { return 0; }; return in; }
cairo_status_to_string_sig* chk_cairo_status_to_string_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_status_to_string_sig* in = (cairo_status_to_string_sig*)(x+1); if( in->lst.len != 1 || INT(status) 0) { return 0; }; return in; }
cairo_device_reference_sig* chk_cairo_device_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_reference_sig* in = (cairo_device_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_get_type_sig* chk_cairo_device_get_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_get_type_sig* in = (cairo_device_get_type_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_status_sig* chk_cairo_device_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_status_sig* in = (cairo_device_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_acquire_sig* chk_cairo_device_acquire_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_acquire_sig* in = (cairo_device_acquire_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_release_sig* chk_cairo_device_release_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_release_sig* in = (cairo_device_release_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_flush_sig* chk_cairo_device_flush_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_flush_sig* in = (cairo_device_flush_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_finish_sig* chk_cairo_device_finish_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_finish_sig* in = (cairo_device_finish_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_destroy_sig* chk_cairo_device_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_destroy_sig* in = (cairo_device_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_get_reference_count_sig* chk_cairo_device_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_get_reference_count_sig* in = (cairo_device_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_get_user_data_sig* chk_cairo_device_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_get_user_data_sig* in = (cairo_device_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(device,KFFI_CAIRO_DEVICE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_device_set_user_data_sig* chk_cairo_device_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_set_user_data_sig* in = (cairo_device_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(device,KFFI_CAIRO_DEVICE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_surface_create_similar_sig* chk_cairo_surface_create_similar_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_create_similar_sig* in = (cairo_surface_create_similar_sig*)(x+1); if( in->lst.len != 4 || TPTR(other,KFFI_CAIRO_SURFACE_T) INT(content) 0) { return 0; }; return in; }
cairo_surface_create_similar_image_sig* chk_cairo_surface_create_similar_image_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_create_similar_image_sig* in = (cairo_surface_create_similar_image_sig*)(x+1); if( in->lst.len != 4 || TPTR(other,KFFI_CAIRO_SURFACE_T) INT(format) 0) { return 0; }; return in; }
cairo_surface_map_to_image_sig* chk_cairo_surface_map_to_image_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_map_to_image_sig* in = (cairo_surface_map_to_image_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(extents,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_surface_unmap_image_sig* chk_cairo_surface_unmap_image_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_unmap_image_sig* in = (cairo_surface_unmap_image_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(image,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_create_for_rectangle_sig* chk_cairo_surface_create_for_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_create_for_rectangle_sig* in = (cairo_surface_create_for_rectangle_sig*)(x+1); if( in->lst.len != 5 || TPTR(target,KFFI_CAIRO_SURFACE_T) DOUBLE(x) DOUBLE(y) DOUBLE(width) DOUBLE(height) 0) { return 0; }; return in; }
cairo_surface_create_observer_sig* chk_cairo_surface_create_observer_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_create_observer_sig* in = (cairo_surface_create_observer_sig*)(x+1); if( in->lst.len != 2 || TPTR(target,KFFI_CAIRO_SURFACE_T) INT(mode) 0) { return 0; }; return in; }
cairo_surface_observer_add_paint_callback_sig* chk_cairo_surface_observer_add_paint_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_paint_callback_sig* in = (cairo_surface_observer_add_paint_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_mask_callback_sig* chk_cairo_surface_observer_add_mask_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_mask_callback_sig* in = (cairo_surface_observer_add_mask_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_fill_callback_sig* chk_cairo_surface_observer_add_fill_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_fill_callback_sig* in = (cairo_surface_observer_add_fill_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_stroke_callback_sig* chk_cairo_surface_observer_add_stroke_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_stroke_callback_sig* in = (cairo_surface_observer_add_stroke_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_glyphs_callback_sig* chk_cairo_surface_observer_add_glyphs_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_glyphs_callback_sig* in = (cairo_surface_observer_add_glyphs_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_flush_callback_sig* chk_cairo_surface_observer_add_flush_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_flush_callback_sig* in = (cairo_surface_observer_add_flush_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_add_finish_callback_sig* chk_cairo_surface_observer_add_finish_callback_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_add_finish_callback_sig* in = (cairo_surface_observer_add_finish_callback_sig*)(x+1); if( in->lst.len != 3 || TPTR(abstract_surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_print_sig* chk_cairo_surface_observer_print_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_print_sig* in = (cairo_surface_observer_print_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_observer_elapsed_sig* chk_cairo_surface_observer_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_observer_elapsed_sig* in = (cairo_surface_observer_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_device_observer_print_sig* chk_cairo_device_observer_print_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_print_sig* in = (cairo_device_observer_print_sig*)(x+1); if( in->lst.len != 3 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_elapsed_sig* chk_cairo_device_observer_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_elapsed_sig* in = (cairo_device_observer_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_paint_elapsed_sig* chk_cairo_device_observer_paint_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_paint_elapsed_sig* in = (cairo_device_observer_paint_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_mask_elapsed_sig* chk_cairo_device_observer_mask_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_mask_elapsed_sig* in = (cairo_device_observer_mask_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_fill_elapsed_sig* chk_cairo_device_observer_fill_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_fill_elapsed_sig* in = (cairo_device_observer_fill_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_stroke_elapsed_sig* chk_cairo_device_observer_stroke_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_stroke_elapsed_sig* in = (cairo_device_observer_stroke_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_device_observer_glyphs_elapsed_sig* chk_cairo_device_observer_glyphs_elapsed_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_device_observer_glyphs_elapsed_sig* in = (cairo_device_observer_glyphs_elapsed_sig*)(x+1); if( in->lst.len != 1 || TPTR(device,KFFI_CAIRO_DEVICE_T) 0) { return 0; }; return in; }
cairo_surface_reference_sig* chk_cairo_surface_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_reference_sig* in = (cairo_surface_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_finish_sig* chk_cairo_surface_finish_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_finish_sig* in = (cairo_surface_finish_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
//cairo_surface_destroy_sig* chk_cairo_surface_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_destroy_sig* in = (cairo_surface_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_get_device_sig* chk_cairo_surface_get_device_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_device_sig* in = (cairo_surface_get_device_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_get_reference_count_sig* chk_cairo_surface_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_reference_count_sig* in = (cairo_surface_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
//cairo_surface_status_sig* chk_cairo_surface_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_status_sig* in = (cairo_surface_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_get_type_sig* chk_cairo_surface_get_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_type_sig* in = (cairo_surface_get_type_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_get_content_sig* chk_cairo_surface_get_content_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_content_sig* in = (cairo_surface_get_content_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_write_to_png_sig* chk_cairo_surface_write_to_png_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_write_to_png_sig* in = (cairo_surface_write_to_png_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) STRING(filename) 0) { return 0; }; return in; }
cairo_surface_write_to_png_stream_sig* chk_cairo_surface_write_to_png_stream_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_write_to_png_stream_sig* in = (cairo_surface_write_to_png_stream_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_get_user_data_sig* chk_cairo_surface_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_user_data_sig* in = (cairo_surface_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_surface_set_user_data_sig* chk_cairo_surface_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_set_user_data_sig* in = (cairo_surface_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_surface_get_mime_data_sig* chk_cairo_surface_get_mime_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_mime_data_sig* in = (cairo_surface_get_mime_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(surface,KFFI_CAIRO_SURFACE_T) STRING(mime_type) 0) { return 0; }; return in; }
cairo_surface_set_mime_data_sig* chk_cairo_surface_set_mime_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_set_mime_data_sig* in = (cairo_surface_set_mime_data_sig*)(x+1); if( in->lst.len != 6 || TPTR(surface,KFFI_CAIRO_SURFACE_T) STRING(mime_type) STRING(data) LONG(length) 0) { return 0; }; return in; }
cairo_surface_supports_mime_type_sig* chk_cairo_surface_supports_mime_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_supports_mime_type_sig* in = (cairo_surface_supports_mime_type_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) STRING(mime_type) 0) { return 0; }; return in; }
cairo_surface_get_font_options_sig* chk_cairo_surface_get_font_options_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_font_options_sig* in = (cairo_surface_get_font_options_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(options,KFFI_CAIRO_FONT_OPTIONS_T) 0) { return 0; }; return in; }
//cairo_surface_flush_sig* chk_cairo_surface_flush_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_flush_sig* in = (cairo_surface_flush_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_mark_dirty_sig* chk_cairo_surface_mark_dirty_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_mark_dirty_sig* in = (cairo_surface_mark_dirty_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_mark_dirty_rectangle_sig* chk_cairo_surface_mark_dirty_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_mark_dirty_rectangle_sig* in = (cairo_surface_mark_dirty_rectangle_sig*)(x+1); if( in->lst.len != 5 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_set_device_scale_sig* chk_cairo_surface_set_device_scale_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_set_device_scale_sig* in = (cairo_surface_set_device_scale_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_scale) DOUBLE(y_scale) 0) { return 0; }; return in; }
cairo_surface_get_device_scale_sig* chk_cairo_surface_get_device_scale_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_device_scale_sig* in = (cairo_surface_get_device_scale_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_scale) DOUBLE(y_scale) 0) { return 0; }; return in; }
cairo_surface_set_device_offset_sig* chk_cairo_surface_set_device_offset_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_set_device_offset_sig* in = (cairo_surface_set_device_offset_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_offset) DOUBLE(y_offset) 0) { return 0; }; return in; }
cairo_surface_get_device_offset_sig* chk_cairo_surface_get_device_offset_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_device_offset_sig* in = (cairo_surface_get_device_offset_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_offset) DOUBLE(y_offset) 0) { return 0; }; return in; }
cairo_surface_set_fallback_resolution_sig* chk_cairo_surface_set_fallback_resolution_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_set_fallback_resolution_sig* in = (cairo_surface_set_fallback_resolution_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_pixels_per_inch) DOUBLE(y_pixels_per_inch) 0) { return 0; }; return in; }
cairo_surface_get_fallback_resolution_sig* chk_cairo_surface_get_fallback_resolution_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_get_fallback_resolution_sig* in = (cairo_surface_get_fallback_resolution_sig*)(x+1); if( in->lst.len != 3 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x_pixels_per_inch) DOUBLE(y_pixels_per_inch) 0) { return 0; }; return in; }
cairo_surface_copy_page_sig* chk_cairo_surface_copy_page_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_copy_page_sig* in = (cairo_surface_copy_page_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_show_page_sig* chk_cairo_surface_show_page_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_show_page_sig* in = (cairo_surface_show_page_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_surface_has_show_text_glyphs_sig* chk_cairo_surface_has_show_text_glyphs_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_surface_has_show_text_glyphs_sig* in = (cairo_surface_has_show_text_glyphs_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_create_sig* chk_cairo_image_surface_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_create_sig* in = (cairo_image_surface_create_sig*)(x+1); if( in->lst.len != 3 || INT(format) 0) { return 0; }; return in; }
//cairo_format_stride_for_width_sig* chk_cairo_format_stride_for_width_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_format_stride_for_width_sig* in = (cairo_format_stride_for_width_sig*)(x+1); if( in->lst.len != 2 || INT(format) 0) { return 0; }; return in; }
cairo_image_surface_create_for_data_sig* chk_cairo_image_surface_create_for_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_create_for_data_sig* in = (cairo_image_surface_create_for_data_sig*)(x+1); if( in->lst.len != 5 || STRING(data) INT(format) INT(height) INT(width) INT(stride) 0) { return 0; }; return in; }
//cairo_image_surface_get_data_sig* chk_cairo_image_surface_get_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_get_data_sig* in = (cairo_image_surface_get_data_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_get_format_sig* chk_cairo_image_surface_get_format_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_get_format_sig* in = (cairo_image_surface_get_format_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_get_width_sig* chk_cairo_image_surface_get_width_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_get_width_sig* in = (cairo_image_surface_get_width_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_get_height_sig* chk_cairo_image_surface_get_height_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_get_height_sig* in = (cairo_image_surface_get_height_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_get_stride_sig* chk_cairo_image_surface_get_stride_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_get_stride_sig* in = (cairo_image_surface_get_stride_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_image_surface_create_from_png_sig* chk_cairo_image_surface_create_from_png_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_create_from_png_sig* in = (cairo_image_surface_create_from_png_sig*)(x+1); if( in->lst.len != 1 || STRING(filename) 0) { return 0; }; return in; }
cairo_image_surface_create_from_png_stream_sig* chk_cairo_image_surface_create_from_png_stream_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_image_surface_create_from_png_stream_sig* in = (cairo_image_surface_create_from_png_stream_sig*)(x+1); if( in->lst.len != 2 || 0) { return 0; }; return in; }
cairo_recording_surface_create_sig* chk_cairo_recording_surface_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_recording_surface_create_sig* in = (cairo_recording_surface_create_sig*)(x+1); if( in->lst.len != 2 || INT(content) TPTR(extents,KFFI_CAIRO_RECTANGLE_T) 0) { return 0; }; return in; }
cairo_recording_surface_ink_extents_sig* chk_cairo_recording_surface_ink_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_recording_surface_ink_extents_sig* in = (cairo_recording_surface_ink_extents_sig*)(x+1); if( in->lst.len != 5 || TPTR(surface,KFFI_CAIRO_SURFACE_T) DOUBLE(x0) DOUBLE(y0) DOUBLE(width) DOUBLE(height) 0) { return 0; }; return in; }
cairo_recording_surface_get_extents_sig* chk_cairo_recording_surface_get_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_recording_surface_get_extents_sig* in = (cairo_recording_surface_get_extents_sig*)(x+1); if( in->lst.len != 2 || TPTR(surface,KFFI_CAIRO_SURFACE_T) TPTR(extents,KFFI_CAIRO_RECTANGLE_T) 0) { return 0; }; return in; }
cairo_pattern_create_raster_source_sig* chk_cairo_pattern_create_raster_source_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_raster_source_sig* in = (cairo_pattern_create_raster_source_sig*)(x+1); if( in->lst.len != 4 || INT(content) 0) { return 0; }; return in; }
cairo_raster_source_pattern_set_callback_data_sig* chk_cairo_raster_source_pattern_set_callback_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_set_callback_data_sig* in = (cairo_raster_source_pattern_set_callback_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_get_callback_data_sig* chk_cairo_raster_source_pattern_get_callback_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_get_callback_data_sig* in = (cairo_raster_source_pattern_get_callback_data_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_set_acquire_sig* chk_cairo_raster_source_pattern_set_acquire_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_set_acquire_sig* in = (cairo_raster_source_pattern_set_acquire_sig*)(x+1); if( in->lst.len != 3 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_get_acquire_sig* chk_cairo_raster_source_pattern_get_acquire_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_get_acquire_sig* in = (cairo_raster_source_pattern_get_acquire_sig*)(x+1); if( in->lst.len != 3 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_set_snapshot_sig* chk_cairo_raster_source_pattern_set_snapshot_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_set_snapshot_sig* in = (cairo_raster_source_pattern_set_snapshot_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_get_snapshot_sig* chk_cairo_raster_source_pattern_get_snapshot_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_get_snapshot_sig* in = (cairo_raster_source_pattern_get_snapshot_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_set_copy_sig* chk_cairo_raster_source_pattern_set_copy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_set_copy_sig* in = (cairo_raster_source_pattern_set_copy_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_get_copy_sig* chk_cairo_raster_source_pattern_get_copy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_get_copy_sig* in = (cairo_raster_source_pattern_get_copy_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_set_finish_sig* chk_cairo_raster_source_pattern_set_finish_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_set_finish_sig* in = (cairo_raster_source_pattern_set_finish_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_raster_source_pattern_get_finish_sig* chk_cairo_raster_source_pattern_get_finish_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_raster_source_pattern_get_finish_sig* in = (cairo_raster_source_pattern_get_finish_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_create_rgb_sig* chk_cairo_pattern_create_rgb_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_rgb_sig* in = (cairo_pattern_create_rgb_sig*)(x+1); if( in->lst.len != 3 || DOUBLE(red) DOUBLE(green) DOUBLE(blue) 0) { return 0; }; return in; }
cairo_pattern_create_rgba_sig* chk_cairo_pattern_create_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_rgba_sig* in = (cairo_pattern_create_rgba_sig*)(x+1); if( in->lst.len != 4 || DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_pattern_create_for_surface_sig* chk_cairo_pattern_create_for_surface_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_for_surface_sig* in = (cairo_pattern_create_for_surface_sig*)(x+1); if( in->lst.len != 1 || TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_pattern_create_linear_sig* chk_cairo_pattern_create_linear_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_linear_sig* in = (cairo_pattern_create_linear_sig*)(x+1); if( in->lst.len != 4 || DOUBLE(x0) DOUBLE(y0) DOUBLE(x1) DOUBLE(y1) 0) { return 0; }; return in; }
cairo_pattern_create_radial_sig* chk_cairo_pattern_create_radial_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_radial_sig* in = (cairo_pattern_create_radial_sig*)(x+1); if( in->lst.len != 6 || DOUBLE(cx0) DOUBLE(cy0) DOUBLE(radius0) DOUBLE(cx1) DOUBLE(cy1) DOUBLE(radius1) 0) { return 0; }; return in; }
//cairo_pattern_create_mesh_sig* chk_cairo_pattern_create_mesh_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_create_mesh_sig* in = (cairo_pattern_create_mesh_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
cairo_pattern_reference_sig* chk_cairo_pattern_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_reference_sig* in = (cairo_pattern_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_destroy_sig* chk_cairo_pattern_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_destroy_sig* in = (cairo_pattern_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_get_reference_count_sig* chk_cairo_pattern_get_reference_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_reference_count_sig* in = (cairo_pattern_get_reference_count_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_status_sig* chk_cairo_pattern_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_status_sig* in = (cairo_pattern_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_get_user_data_sig* chk_cairo_pattern_get_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_user_data_sig* in = (cairo_pattern_get_user_data_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_pattern_set_user_data_sig* chk_cairo_pattern_set_user_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_set_user_data_sig* in = (cairo_pattern_set_user_data_sig*)(x+1); if( in->lst.len != 4 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) TPTR(key,KFFI_CAIRO_USER_DATA_KEY_T) 0) { return 0; }; return in; }
cairo_pattern_get_type_sig* chk_cairo_pattern_get_type_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_type_sig* in = (cairo_pattern_get_type_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_add_color_stop_rgb_sig* chk_cairo_pattern_add_color_stop_rgb_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_add_color_stop_rgb_sig* in = (cairo_pattern_add_color_stop_rgb_sig*)(x+1); if( in->lst.len != 5 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(offset) DOUBLE(red) DOUBLE(green) DOUBLE(blue) 0) { return 0; }; return in; }
cairo_pattern_add_color_stop_rgba_sig* chk_cairo_pattern_add_color_stop_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_add_color_stop_rgba_sig* in = (cairo_pattern_add_color_stop_rgba_sig*)(x+1); if( in->lst.len != 6 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(offset) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_mesh_pattern_begin_patch_sig* chk_cairo_mesh_pattern_begin_patch_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_begin_patch_sig* in = (cairo_mesh_pattern_begin_patch_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_mesh_pattern_end_patch_sig* chk_cairo_mesh_pattern_end_patch_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_end_patch_sig* in = (cairo_mesh_pattern_end_patch_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_mesh_pattern_curve_to_sig* chk_cairo_mesh_pattern_curve_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_curve_to_sig* in = (cairo_mesh_pattern_curve_to_sig*)(x+1); if( in->lst.len != 7 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x1) DOUBLE(y1) DOUBLE(x2) DOUBLE(y2) DOUBLE(x3) DOUBLE(y3) 0) { return 0; }; return in; }
cairo_mesh_pattern_line_to_sig* chk_cairo_mesh_pattern_line_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_line_to_sig* in = (cairo_mesh_pattern_line_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_mesh_pattern_move_to_sig* chk_cairo_mesh_pattern_move_to_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_move_to_sig* in = (cairo_mesh_pattern_move_to_sig*)(x+1); if( in->lst.len != 3 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_mesh_pattern_set_control_point_sig* chk_cairo_mesh_pattern_set_control_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_set_control_point_sig* in = (cairo_mesh_pattern_set_control_point_sig*)(x+1); if( in->lst.len != 4 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_mesh_pattern_set_corner_color_rgb_sig* chk_cairo_mesh_pattern_set_corner_color_rgb_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_set_corner_color_rgb_sig* in = (cairo_mesh_pattern_set_corner_color_rgb_sig*)(x+1); if( in->lst.len != 5 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(red) DOUBLE(green) DOUBLE(blue) 0) { return 0; }; return in; }
cairo_mesh_pattern_set_corner_color_rgba_sig* chk_cairo_mesh_pattern_set_corner_color_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_set_corner_color_rgba_sig* in = (cairo_mesh_pattern_set_corner_color_rgba_sig*)(x+1); if( in->lst.len != 6 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_pattern_set_matrix_sig* chk_cairo_pattern_set_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_set_matrix_sig* in = (cairo_pattern_set_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_pattern_get_matrix_sig* chk_cairo_pattern_get_matrix_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_matrix_sig* in = (cairo_pattern_get_matrix_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_pattern_set_extend_sig* chk_cairo_pattern_set_extend_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_set_extend_sig* in = (cairo_pattern_set_extend_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) INT(extend) 0) { return 0; }; return in; }
cairo_pattern_get_extend_sig* chk_cairo_pattern_get_extend_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_extend_sig* in = (cairo_pattern_get_extend_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_set_filter_sig* chk_cairo_pattern_set_filter_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_set_filter_sig* in = (cairo_pattern_set_filter_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) INT(filter) 0) { return 0; }; return in; }
cairo_pattern_get_filter_sig* chk_cairo_pattern_get_filter_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_filter_sig* in = (cairo_pattern_get_filter_sig*)(x+1); if( in->lst.len != 1 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_get_rgba_sig* chk_cairo_pattern_get_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_rgba_sig* in = (cairo_pattern_get_rgba_sig*)(x+1); if( in->lst.len != 5 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_pattern_get_surface_sig* chk_cairo_pattern_get_surface_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_surface_sig* in = (cairo_pattern_get_surface_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) TPTR(surface,KFFI_CAIRO_SURFACE_T) 0) { return 0; }; return in; }
cairo_pattern_get_color_stop_rgba_sig* chk_cairo_pattern_get_color_stop_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_color_stop_rgba_sig* in = (cairo_pattern_get_color_stop_rgba_sig*)(x+1); if( in->lst.len != 7 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(offset) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_pattern_get_color_stop_count_sig* chk_cairo_pattern_get_color_stop_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_color_stop_count_sig* in = (cairo_pattern_get_color_stop_count_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_pattern_get_linear_points_sig* chk_cairo_pattern_get_linear_points_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_linear_points_sig* in = (cairo_pattern_get_linear_points_sig*)(x+1); if( in->lst.len != 5 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x0) DOUBLE(y0) DOUBLE(x1) DOUBLE(y1) 0) { return 0; }; return in; }
cairo_pattern_get_radial_circles_sig* chk_cairo_pattern_get_radial_circles_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_pattern_get_radial_circles_sig* in = (cairo_pattern_get_radial_circles_sig*)(x+1); if( in->lst.len != 7 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x0) DOUBLE(y0) DOUBLE(r0) DOUBLE(x1) DOUBLE(y1) DOUBLE(r1) 0) { return 0; }; return in; }
cairo_mesh_pattern_get_patch_count_sig* chk_cairo_mesh_pattern_get_patch_count_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_get_patch_count_sig* in = (cairo_mesh_pattern_get_patch_count_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_mesh_pattern_get_path_sig* chk_cairo_mesh_pattern_get_path_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_get_path_sig* in = (cairo_mesh_pattern_get_path_sig*)(x+1); if( in->lst.len != 2 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) 0) { return 0; }; return in; }
cairo_mesh_pattern_get_corner_color_rgba_sig* chk_cairo_mesh_pattern_get_corner_color_rgba_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_get_corner_color_rgba_sig* in = (cairo_mesh_pattern_get_corner_color_rgba_sig*)(x+1); if( in->lst.len != 7 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(red) DOUBLE(green) DOUBLE(blue) DOUBLE(alpha) 0) { return 0; }; return in; }
cairo_mesh_pattern_get_control_point_sig* chk_cairo_mesh_pattern_get_control_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_mesh_pattern_get_control_point_sig* in = (cairo_mesh_pattern_get_control_point_sig*)(x+1); if( in->lst.len != 5 || TPTR(pattern,KFFI_CAIRO_PATTERN_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
cairo_matrix_init_sig* chk_cairo_matrix_init_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_init_sig* in = (cairo_matrix_init_sig*)(x+1); if( in->lst.len != 7 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(xx) DOUBLE(yx) DOUBLE(xy) DOUBLE(yy) DOUBLE(x0) DOUBLE(y0) 0) { return 0; }; return in; }
cairo_matrix_init_identity_sig* chk_cairo_matrix_init_identity_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_init_identity_sig* in = (cairo_matrix_init_identity_sig*)(x+1); if( in->lst.len != 1 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_matrix_init_translate_sig* chk_cairo_matrix_init_translate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_init_translate_sig* in = (cairo_matrix_init_translate_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(tx) DOUBLE(ty) 0) { return 0; }; return in; }
cairo_matrix_init_scale_sig* chk_cairo_matrix_init_scale_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_init_scale_sig* in = (cairo_matrix_init_scale_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(sx) DOUBLE(sy) 0) { return 0; }; return in; }
cairo_matrix_init_rotate_sig* chk_cairo_matrix_init_rotate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_init_rotate_sig* in = (cairo_matrix_init_rotate_sig*)(x+1); if( in->lst.len != 2 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(radians) 0) { return 0; }; return in; }
cairo_matrix_translate_sig* chk_cairo_matrix_translate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_translate_sig* in = (cairo_matrix_translate_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(tx) DOUBLE(ty) 0) { return 0; }; return in; }
cairo_matrix_scale_sig* chk_cairo_matrix_scale_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_scale_sig* in = (cairo_matrix_scale_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(sx) DOUBLE(sy) 0) { return 0; }; return in; }
cairo_matrix_rotate_sig* chk_cairo_matrix_rotate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_rotate_sig* in = (cairo_matrix_rotate_sig*)(x+1); if( in->lst.len != 2 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(radians) 0) { return 0; }; return in; }
cairo_matrix_invert_sig* chk_cairo_matrix_invert_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_invert_sig* in = (cairo_matrix_invert_sig*)(x+1); if( in->lst.len != 1 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_matrix_multiply_sig* chk_cairo_matrix_multiply_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_multiply_sig* in = (cairo_matrix_multiply_sig*)(x+1); if( in->lst.len != 3 || TPTR(result,KFFI_CAIRO_MATRIX_T) TPTR(a,KFFI_CAIRO_MATRIX_T) TPTR(b,KFFI_CAIRO_MATRIX_T) 0) { return 0; }; return in; }
cairo_matrix_transform_distance_sig* chk_cairo_matrix_transform_distance_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_transform_distance_sig* in = (cairo_matrix_transform_distance_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(dx) DOUBLE(dy) 0) { return 0; }; return in; }
cairo_matrix_transform_point_sig* chk_cairo_matrix_transform_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_matrix_transform_point_sig* in = (cairo_matrix_transform_point_sig*)(x+1); if( in->lst.len != 3 || TPTR(matrix,KFFI_CAIRO_MATRIX_T) DOUBLE(x) DOUBLE(y) 0) { return 0; }; return in; }
//cairo_region_create_sig* chk_cairo_region_create_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_create_sig* in = (cairo_region_create_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
cairo_region_create_rectangle_sig* chk_cairo_region_create_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_create_rectangle_sig* in = (cairo_region_create_rectangle_sig*)(x+1); if( in->lst.len != 1 || TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_create_rectangles_sig* chk_cairo_region_create_rectangles_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_create_rectangles_sig* in = (cairo_region_create_rectangles_sig*)(x+1); if( in->lst.len != 2 || TPTR(rects,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_copy_sig* chk_cairo_region_copy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_copy_sig* in = (cairo_region_copy_sig*)(x+1); if( in->lst.len != 1 || TPTR(original,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_reference_sig* chk_cairo_region_reference_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_reference_sig* in = (cairo_region_reference_sig*)(x+1); if( in->lst.len != 1 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_destroy_sig* chk_cairo_region_destroy_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_destroy_sig* in = (cairo_region_destroy_sig*)(x+1); if( in->lst.len != 1 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_equal_sig* chk_cairo_region_equal_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_equal_sig* in = (cairo_region_equal_sig*)(x+1); if( in->lst.len != 2 || TPTR(a,KFFI_CAIRO_REGION_T) TPTR(b,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_status_sig* chk_cairo_region_status_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_status_sig* in = (cairo_region_status_sig*)(x+1); if( in->lst.len != 1 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_get_extents_sig* chk_cairo_region_get_extents_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_get_extents_sig* in = (cairo_region_get_extents_sig*)(x+1); if( in->lst.len != 2 || TPTR(region,KFFI_CAIRO_REGION_T) TPTR(extents,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_num_rectangles_sig* chk_cairo_region_num_rectangles_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_num_rectangles_sig* in = (cairo_region_num_rectangles_sig*)(x+1); if( in->lst.len != 1 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_get_rectangle_sig* chk_cairo_region_get_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_get_rectangle_sig* in = (cairo_region_get_rectangle_sig*)(x+1); if( in->lst.len != 3 || TPTR(region,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_is_empty_sig* chk_cairo_region_is_empty_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_is_empty_sig* in = (cairo_region_is_empty_sig*)(x+1); if( in->lst.len != 1 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_contains_rectangle_sig* chk_cairo_region_contains_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_contains_rectangle_sig* in = (cairo_region_contains_rectangle_sig*)(x+1); if( in->lst.len != 2 || TPTR(region,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_contains_point_sig* chk_cairo_region_contains_point_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_contains_point_sig* in = (cairo_region_contains_point_sig*)(x+1); if( in->lst.len != 3 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_translate_sig* chk_cairo_region_translate_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_translate_sig* in = (cairo_region_translate_sig*)(x+1); if( in->lst.len != 3 || TPTR(region,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_subtract_sig* chk_cairo_region_subtract_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_subtract_sig* in = (cairo_region_subtract_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(other,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_subtract_rectangle_sig* chk_cairo_region_subtract_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_subtract_rectangle_sig* in = (cairo_region_subtract_rectangle_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_intersect_sig* chk_cairo_region_intersect_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_intersect_sig* in = (cairo_region_intersect_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(other,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_intersect_rectangle_sig* chk_cairo_region_intersect_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_intersect_rectangle_sig* in = (cairo_region_intersect_rectangle_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_union_sig* chk_cairo_region_union_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_union_sig* in = (cairo_region_union_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(other,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_union_rectangle_sig* chk_cairo_region_union_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_union_rectangle_sig* in = (cairo_region_union_rectangle_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
cairo_region_xor_sig* chk_cairo_region_xor_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_xor_sig* in = (cairo_region_xor_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(other,KFFI_CAIRO_REGION_T) 0) { return 0; }; return in; }
cairo_region_xor_rectangle_sig* chk_cairo_region_xor_rectangle_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_region_xor_rectangle_sig* in = (cairo_region_xor_rectangle_sig*)(x+1); if( in->lst.len != 2 || TPTR(dst,KFFI_CAIRO_REGION_T) TPTR(rectangle,KFFI_CAIRO_RECTANGLE_INT_T) 0) { return 0; }; return in; }
//cairo_debug_reset_static_data_sig* chk_cairo_debug_reset_static_data_sig(S x){ if (x[0] != VER || x[1] != 1) return 0; cairo_debug_reset_static_data_sig* in = (cairo_debug_reset_static_data_sig*)(x+1); if( in->lst.len != 0 || 0) { return 0; }; return in; }
