#ifndef FCAIRO_TYPEDEFS_H
#define FCAIRO_TYPEDEFS_H
typedef long long L;typedef unsigned int U;

typedef struct __attribute__((packed)) { char type; uint32_t len; } hdr;
typedef struct __attribute__((packed)) { hdr hdr; void* arr; } arr;

//typedef struct __attribute__((packed)) {hdr lst;} cairo_version_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_version_string_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr target;} cairo_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_reference_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_reference_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr key;} cairo_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr key;} cairo_set_user_data_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_save_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_restore_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_push_group_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typcontent; L content;} cairo_push_group_with_content_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_pop_group_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_pop_group_to_source_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typop; L op;} cairo_set_operator_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr source;} cairo_set_source_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr red; arr green; arr blue;} cairo_set_source_rgb_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr red; arr green; arr blue; arr alpha;} cairo_set_source_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr surface; arr x; arr y;} cairo_set_source_surface_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr tolerance;} cairo_set_tolerance_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typantialias; L antialias;} cairo_set_antialias_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typfill_rule; L fill_rule;} cairo_set_fill_rule_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr width;} cairo_set_line_width_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typset_hairline; L set_hairline;} cairo_set_hairline_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typline_cap; L line_cap;} cairo_set_line_cap_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; C typline_join; L line_join;} cairo_set_line_join_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dashes; C typnum_dashes; L num_dashes; arr offset;} cairo_set_dash_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr limit;} cairo_set_miter_limit_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr tx; arr ty;} cairo_translate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr sx; arr sy;} cairo_scale_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr angle;} cairo_rotate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr matrix;} cairo_transform_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr matrix;} cairo_set_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_identity_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_user_to_device_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dx; arr dy;} cairo_user_to_device_distance_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_device_to_user_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dx; arr dy;} cairo_device_to_user_distance_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_new_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_move_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_new_sub_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_line_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x1; arr y1; arr x2; arr y2; arr x3; arr y3;} cairo_curve_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr xc; arr yc; arr radius; arr angle1; arr angle2;} cairo_arc_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr xc; arr yc; arr radius; arr angle1; arr angle2;} cairo_arc_negative_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dx; arr dy;} cairo_rel_move_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dx; arr dy;} cairo_rel_line_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dx1; arr dy1; arr dx2; arr dy2; arr dx3; arr dy3;} cairo_rel_curve_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y; arr width; arr height;} cairo_rectangle_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_close_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x1; arr y1; arr x2; arr y2;} cairo_path_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_paint_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr alpha;} cairo_paint_with_alpha_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr pattern;} cairo_mask_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr surface; arr surface_x; arr surface_y;} cairo_mask_surface_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_stroke_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_stroke_preserve_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_fill_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_fill_preserve_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_copy_page_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_show_page_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_in_stroke_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_in_fill_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_in_clip_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x1; arr y1; arr x2; arr y2;} cairo_stroke_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x1; arr y1; arr x2; arr y2;} cairo_fill_extents_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_reset_clip_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_clip_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_clip_preserve_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x1; arr y1; arr x2; arr y2;} cairo_clip_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_copy_clip_rectangle_list_sig;
typedef struct __attribute__((packed)) {hdr lst;arr rectangle_list;} cairo_rectangle_list_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr tag_name; arr attributes; } cairo_tag_begin_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr tag_name;} cairo_tag_end_sig;
typedef struct __attribute__((packed)) {hdr lst;C typnum_glyphs; L num_glyphs;} cairo_glyph_allocate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr glyphs;} cairo_glyph_free_sig;
typedef struct __attribute__((packed)) {hdr lst;C typnum_clusters; L num_clusters;} cairo_text_cluster_allocate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr clusters;} cairo_text_cluster_free_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_font_options_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr original;} cairo_font_options_copy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; arr other;} cairo_font_options_merge_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; arr other;} cairo_font_options_equal_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_hash_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; C typantialias; L antialias;} cairo_font_options_set_antialias_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_get_antialias_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; C typsubpixel_order; L subpixel_order;} cairo_font_options_set_subpixel_order_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_get_subpixel_order_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; C typhint_style; L hint_style;} cairo_font_options_set_hint_style_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_get_hint_style_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; C typhint_metrics; L hint_metrics;} cairo_font_options_set_hint_metrics_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_get_hint_metrics_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options;} cairo_font_options_get_variations_sig;
typedef struct __attribute__((packed)) {hdr lst;arr options; arr variations;} cairo_font_options_set_variations_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr family; C typslant; L slant; C typweight; L weight;} cairo_select_font_face_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr size;} cairo_set_font_size_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr matrix;} cairo_set_font_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr matrix;} cairo_get_font_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr options;} cairo_set_font_options_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr options;} cairo_get_font_options_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr font_face;} cairo_set_font_face_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_font_face_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr scaled_font;} cairo_set_scaled_font_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_scaled_font_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr utf8;} cairo_show_text_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr glyphs; C typnum_glyphs; L num_glyphs;} cairo_show_glyphs_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr utf8; C typutf8_len; L utf8_len; arr glyphs; C typnum_glyphs; L num_glyphs; arr clusters; C typnum_clusters; L num_clusters; C typcluster_flags; L cluster_flags;} cairo_show_text_glyphs_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr utf8;} cairo_text_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr glyphs; C typnum_glyphs; L num_glyphs;} cairo_glyph_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr utf8;} cairo_text_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr glyphs; C typnum_glyphs; L num_glyphs; arr extents;} cairo_glyph_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr extents;} cairo_font_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_font_face_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_font_face_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_font_face_get_reference_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_font_face_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_font_face_get_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face; arr key;} cairo_font_face_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face; arr key;} cairo_font_face_set_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face; arr font_matrix; arr ctm; arr options;} cairo_scaled_font_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_get_reference_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_get_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr key;} cairo_scaled_font_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr key;} cairo_scaled_font_set_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr extents;} cairo_scaled_font_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr utf8; arr extents;} cairo_scaled_font_text_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr glyphs; C typnum_glyphs; L num_glyphs; arr extents;} cairo_scaled_font_glyph_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr x; arr y; arr utf8; C typutf8_len; L utf8_len;} cairo_scaled_font_text_to_glyphs_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font;} cairo_scaled_font_get_font_face_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr font_matrix;} cairo_scaled_font_get_font_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr ctm;} cairo_scaled_font_get_ctm_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr scale_matrix;} cairo_scaled_font_get_scale_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr scaled_font; arr options;} cairo_scaled_font_get_font_options_sig;
typedef struct __attribute__((packed)) {hdr lst;arr family; C typslant; L slant; C typweight; L weight;} cairo_toy_font_face_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_toy_font_face_get_family_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_toy_font_face_get_slant_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_toy_font_face_get_weight_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_user_font_face_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_set_init_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_set_render_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_set_render_color_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_set_text_to_glyphs_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_set_unicode_to_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_get_init_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_get_render_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_get_render_color_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_get_text_to_glyphs_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr font_face;} cairo_user_font_face_get_unicode_to_glyph_func_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_operator_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_source_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_tolerance_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_antialias_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_has_current_point_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr x; arr y;} cairo_get_current_point_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_fill_rule_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_line_width_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_hairline_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_line_cap_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_line_join_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_miter_limit_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_dash_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr dashes; arr offset;} cairo_get_dash_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr matrix;} cairo_get_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_target_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_get_group_target_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_copy_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_copy_path_flat_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cr; arr path;} cairo_append_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr path;} cairo_path_destroy_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr cr;} cairo_status_sig;
typedef struct __attribute__((packed)) {hdr lst;C typstatus; L status;} cairo_status_to_string_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_get_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_acquire_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_release_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_flush_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_finish_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_get_reference_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device; arr key;} cairo_device_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device; arr key;} cairo_device_set_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr other; C typcontent; L content; C typwidth; L width; C typheight; L height;} cairo_surface_create_similar_sig;
typedef struct __attribute__((packed)) {hdr lst;arr other; C typformat; L format; C typwidth; L width; C typheight; L height;} cairo_surface_create_similar_image_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr extents;} cairo_surface_map_to_image_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr image;} cairo_surface_unmap_image_sig;
typedef struct __attribute__((packed)) {hdr lst;arr target; arr x; arr y; arr width; arr height;} cairo_surface_create_for_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr target; C typmode; L mode;} cairo_surface_create_observer_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_paint_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_mask_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_fill_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_stroke_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_glyphs_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_flush_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr abstract_surface;} cairo_surface_observer_add_finish_callback_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_observer_print_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_observer_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_print_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_paint_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_mask_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_fill_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_stroke_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr device;} cairo_device_observer_glyphs_elapsed_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_finish_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_get_device_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_get_reference_count_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_get_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_get_content_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr filename;} cairo_surface_write_to_png_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_write_to_png_stream_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr key;} cairo_surface_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr key;} cairo_surface_set_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr mime_type;} cairo_surface_get_mime_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr mime_type; arr data; arr length;} cairo_surface_set_mime_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr mime_type;} cairo_surface_supports_mime_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr options;} cairo_surface_get_font_options_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_flush_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_mark_dirty_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; C typx; L x; C typy; L y; C typwidth; L width; C typheight; L height;} cairo_surface_mark_dirty_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_scale; arr y_scale;} cairo_surface_set_device_scale_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_scale; arr y_scale;} cairo_surface_get_device_scale_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_offset; arr y_offset;} cairo_surface_set_device_offset_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_offset; arr y_offset;} cairo_surface_get_device_offset_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_pixels_per_inch; arr y_pixels_per_inch;} cairo_surface_set_fallback_resolution_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x_pixels_per_inch; arr y_pixels_per_inch;} cairo_surface_get_fallback_resolution_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_copy_page_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_show_page_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_surface_has_show_text_glyphs_sig;
typedef struct __attribute__((packed)) {hdr lst;C typformat; L format; C typwidth; L width; C typheight; L height;} cairo_image_surface_create_sig;
//typedef struct __attribute__((packed)) {hdr lst;C typformat; L format; C typwidth; L width;} cairo_format_stride_for_width_sig;
typedef struct __attribute__((packed)) {hdr lst;arr data; C typformat; L format; C typwidth; L width; C typheight; L height; C typstride; L stride;} cairo_image_surface_create_for_data_sig;
//typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_image_surface_get_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_image_surface_get_format_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_image_surface_get_width_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_image_surface_get_height_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_image_surface_get_stride_sig;
typedef struct __attribute__((packed)) {hdr lst;arr filename;} cairo_image_surface_create_from_png_sig;
typedef struct __attribute__((packed)) {hdr lst;} cairo_image_surface_create_from_png_stream_sig;
typedef struct __attribute__((packed)) {hdr lst;C typcontent; L content; arr extents;} cairo_recording_surface_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr x0; arr y0; arr width; arr height;} cairo_recording_surface_ink_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface; arr extents;} cairo_recording_surface_get_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;C typcontent; L content; C typwidth; L width; C typheight; L height;} cairo_pattern_create_raster_source_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_set_callback_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_get_callback_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_set_acquire_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_get_acquire_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_set_snapshot_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_get_snapshot_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_set_copy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_get_copy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_set_finish_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_raster_source_pattern_get_finish_sig;
typedef struct __attribute__((packed)) {hdr lst;arr red; arr green; arr blue;} cairo_pattern_create_rgb_sig;
typedef struct __attribute__((packed)) {hdr lst;arr red; arr green; arr blue; arr alpha;} cairo_pattern_create_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr surface;} cairo_pattern_create_for_surface_sig;
typedef struct __attribute__((packed)) {hdr lst;arr x0; arr y0; arr x1; arr y1;} cairo_pattern_create_linear_sig;
typedef struct __attribute__((packed)) {hdr lst;arr cx0; arr cy0; arr radius0; arr cx1; arr cy1; arr radius1;} cairo_pattern_create_radial_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_pattern_create_mesh_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_get_reference_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr key;} cairo_pattern_get_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr key;} cairo_pattern_set_user_data_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_get_type_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr offset; arr red; arr green; arr blue;} cairo_pattern_add_color_stop_rgb_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr offset; arr red; arr green; arr blue; arr alpha;} cairo_pattern_add_color_stop_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_mesh_pattern_begin_patch_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_mesh_pattern_end_patch_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr x1; arr y1; arr x2; arr y2; arr x3; arr y3;} cairo_mesh_pattern_curve_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr x; arr y;} cairo_mesh_pattern_line_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr x; arr y;} cairo_mesh_pattern_move_to_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typpoint_num; L point_num; arr x; arr y;} cairo_mesh_pattern_set_control_point_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typcorner_num; L corner_num; arr red; arr green; arr blue;} cairo_mesh_pattern_set_corner_color_rgb_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typcorner_num; L corner_num; arr red; arr green; arr blue; arr alpha;} cairo_mesh_pattern_set_corner_color_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr matrix;} cairo_pattern_set_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr matrix;} cairo_pattern_get_matrix_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typextend; L extend;} cairo_pattern_set_extend_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_get_extend_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typfilter; L filter;} cairo_pattern_set_filter_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_get_filter_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr red; arr green; arr blue; arr alpha;} cairo_pattern_get_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr surface;} cairo_pattern_get_surface_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typindex; L index; arr offset; arr red; arr green; arr blue; arr alpha;} cairo_pattern_get_color_stop_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_pattern_get_color_stop_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr x0; arr y0; arr x1; arr y1;} cairo_pattern_get_linear_points_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; arr x0; arr y0; arr r0; arr x1; arr y1; arr r1;} cairo_pattern_get_radial_circles_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern;} cairo_mesh_pattern_get_patch_count_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typpatch_num; L patch_num;} cairo_mesh_pattern_get_path_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typpatch_num; L patch_num; C typcorner_num; L corner_num; arr red; arr green; arr blue; arr alpha;} cairo_mesh_pattern_get_corner_color_rgba_sig;
typedef struct __attribute__((packed)) {hdr lst;arr pattern; C typpatch_num; L patch_num; C typpoint_num; L point_num; arr x; arr y;} cairo_mesh_pattern_get_control_point_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr xx; arr yx; arr xy; arr yy; arr x0; arr y0;} cairo_matrix_init_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix;} cairo_matrix_init_identity_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr tx; arr ty;} cairo_matrix_init_translate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr sx; arr sy;} cairo_matrix_init_scale_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr radians;} cairo_matrix_init_rotate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr tx; arr ty;} cairo_matrix_translate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr sx; arr sy;} cairo_matrix_scale_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr radians;} cairo_matrix_rotate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix;} cairo_matrix_invert_sig;
typedef struct __attribute__((packed)) {hdr lst;arr result; arr a; arr b;} cairo_matrix_multiply_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr dx; arr dy;} cairo_matrix_transform_distance_sig;
typedef struct __attribute__((packed)) {hdr lst;arr matrix; arr x; arr y;} cairo_matrix_transform_point_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_region_create_sig;
typedef struct __attribute__((packed)) {hdr lst;arr rectangle;} cairo_region_create_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr rects; C typcount; L count;} cairo_region_create_rectangles_sig;
typedef struct __attribute__((packed)) {hdr lst;arr original;} cairo_region_copy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region;} cairo_region_reference_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region;} cairo_region_destroy_sig;
typedef struct __attribute__((packed)) {hdr lst;arr a; arr b;} cairo_region_equal_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region;} cairo_region_status_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region; arr extents;} cairo_region_get_extents_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region;} cairo_region_num_rectangles_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region; C typnth; L nth; arr rectangle;} cairo_region_get_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region;} cairo_region_is_empty_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region; arr rectangle;} cairo_region_contains_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region; C typx; L x; C typy; L y;} cairo_region_contains_point_sig;
typedef struct __attribute__((packed)) {hdr lst;arr region; C typdx; L dx; C typdy; L dy;} cairo_region_translate_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr other;} cairo_region_subtract_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr rectangle;} cairo_region_subtract_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr other;} cairo_region_intersect_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr rectangle;} cairo_region_intersect_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr other;} cairo_region_union_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr rectangle;} cairo_region_union_rectangle_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr other;} cairo_region_xor_sig;
typedef struct __attribute__((packed)) {hdr lst;arr dst; arr rectangle;} cairo_region_xor_rectangle_sig;
//typedef struct __attribute__((packed)) {hdr lst;} cairo_debug_reset_static_data_sig;
#endif
