typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } isamax_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } idamax_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } icamax_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } izamax_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } sasum_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } dasum_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } scasum_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } dzasum_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; } saxpy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; } daxpy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; } caxpy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; } zaxpy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } scopy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } dcopy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } ccopy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } zcopy_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } sdot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } ddot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } cdotu_sub_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } zdotu_sub_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } cdotc_sub_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } zdotc_sub_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; } sdsdot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } dsdot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } snrm2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } dnrm2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } scnrm2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; } dznrm2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr C; arr S; } srot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr C; arr S; } drot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr C; arr S; } csrot_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr C; arr S; } zdrot_sig;
/* typedef struct __attribute__((packed)) { hdr lst; arr A; arr B; arr C; arr S; } srotg_sig; */
/* typedef struct __attribute__((packed)) { hdr lst; arr A; arr B; arr C; arr S; } drotg_sig; */
/* typedef struct __attribute__((packed)) { hdr lst; arr A; arr B; arr C; arr S; } crotg_sig; */
/* typedef struct __attribute__((packed)) { hdr lst; arr A; arr B; arr C; arr S; } zrotg_sig; */
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr P; } srotm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; arr P; } drotm_sig;
/* typedef struct __attribute__((packed)) { hdr lst; arr D1; arr D2; arr B1; arr B2; arr P; } srotmg_sig; */
/* typedef struct __attribute__((packed)) { hdr lst; arr D1; arr D2; arr B1; arr B2; arr P; } drotmg_sig; */
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } sscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } dscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } cscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } zscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } csscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; arr ALPHA; cb_stride X; } zdscal_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } sswap_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } dswap_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } cswap_sig;
typedef struct __attribute__((packed)) { hdr lst; C typN; L N; cb_stride X; cb_stride Y; } zswap_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } sgemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } dgemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } cgemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } zgemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; C typKL; L KL; C typKU; L KU; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } sgbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; C typKL; L KL; C typKU; L KU; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } dgbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; C typKL; L KL; C typKU; L KU; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } cgbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typM; L M; C typN; L N; C typKL; L KL; C typKU; L KU; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } zgbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } sger_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } dger_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } cgerc_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } zgerc_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } cgeru_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typM; L M; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } zgeru_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } chbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } zhbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } chemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } zhemv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_matrix A; } cher_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_matrix A; } zher_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } cher2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } zher2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; arr AP; cb_stride X; arr BETA; cb_stride Y; } chpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; arr AP; cb_stride X; arr BETA; cb_stride Y; } zhpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; arr A; } chpr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; arr A; } zhpr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; arr AP; } chpr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; arr AP; } zhpr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } ssbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } dsbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; arr AP; cb_stride X; arr BETA; cb_stride Y; } sspmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; arr AP; cb_stride X; arr BETA; cb_stride Y; } dspmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; arr AP; } sspr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; arr AP; } dspr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; arr A; } sspr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; arr A; } dspr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } ssymv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_matrix A; cb_stride X; arr BETA; cb_stride Y; } dsymv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_matrix A; } ssyr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_matrix A; } dsyr_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } ssyr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typN; L N; arr ALPHA; cb_stride X; cb_stride Y; cb_matrix A; } dsyr2_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } stbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } dtbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } ctbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } ztbmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } stbsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } dtbsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } ctbsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; C typK; L K; cb_matrix A; cb_stride X; } ztbsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } stpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } dtpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } ctpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } ztpmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } stpsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } dtpsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } ctpsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; arr AP; cb_stride X; } ztpsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } strmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } dtrmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } ctrmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } ztrmv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } strsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } dtrsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } ctrsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typN; L N; cb_matrix A; cb_stride X; } ztrsv_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typTRANSB; L TRANSB; C typM; L M; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } sgemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typTRANSB; L TRANSB; C typM; L M; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } dgemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typTRANSB; L TRANSB; C typM; L M; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } cgemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typTRANSA; L TRANSA; C typTRANSB; L TRANSB; C typM; L M; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } zgemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } chemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } zhemm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } cherk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } zherk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } cher2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } zher2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } ssymm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } dsymm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } csymm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } zsymm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } ssyrk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } dsyrk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } csyrk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; arr BETA; cb_matrix C; } zsyrk_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } ssyr2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } dsyr2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } csyr2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typUPLO; L UPLO; C typTRANS; L TRANS; C typN; L N; C typK; L K; arr ALPHA; cb_matrix A; cb_matrix B; arr BETA; cb_matrix C; } zsyr2k_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } strmm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } dtrmm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } ctrmm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } ztrmm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } strsm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } dtrsm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } ctrsm_sig;
typedef struct __attribute__((packed)) { hdr lst; C typORDER; L ORDER; C typSIDE; L SIDE; C typUPLO; L UPLO; C typTRANSA; L TRANSA; C typDIAG; L DIAG; C typM; L M; C typN; L N; arr ALPHA; cb_matrix A; cb_matrix B; } ztrsm_sig;
isamax_sig* chk_isamax_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; isamax_sig* in = (isamax_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
idamax_sig* chk_idamax_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; idamax_sig* in = (idamax_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
icamax_sig* chk_icamax_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; icamax_sig* in = (icamax_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
izamax_sig* chk_izamax_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; izamax_sig* in = (izamax_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
sasum_sig* chk_sasum_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sasum_sig* in = (sasum_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dasum_sig* chk_dasum_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dasum_sig* in = (dasum_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
scasum_sig* chk_scasum_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; scasum_sig* in = (scasum_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dzasum_sig* chk_dzasum_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dzasum_sig* in = (dzasum_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
saxpy_sig* chk_saxpy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; saxpy_sig* in = (saxpy_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
daxpy_sig* chk_daxpy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; daxpy_sig* in = (daxpy_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
caxpy_sig* chk_caxpy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; caxpy_sig* in = (caxpy_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zaxpy_sig* chk_zaxpy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zaxpy_sig* in = (zaxpy_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
scopy_sig* chk_scopy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; scopy_sig* in = (scopy_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dcopy_sig* chk_dcopy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dcopy_sig* in = (dcopy_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
ccopy_sig* chk_ccopy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ccopy_sig* in = (ccopy_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zcopy_sig* chk_zcopy_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zcopy_sig* in = (zcopy_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sdot_sig* chk_sdot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sdot_sig* in = (sdot_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
ddot_sig* chk_ddot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ddot_sig* in = (ddot_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
cdotu_sub_sig* chk_cdotu_sub_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cdotu_sub_sig* in = (cdotu_sub_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || 0) { return 0; }; return in; }
zdotu_sub_sig* chk_zdotu_sub_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zdotu_sub_sig* in = (zdotu_sub_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || 0) { return 0; }; return in; }
cdotc_sub_sig* chk_cdotc_sub_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cdotc_sub_sig* in = (cdotc_sub_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || 0) { return 0; }; return in; }
zdotc_sub_sig* chk_zdotc_sub_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zdotc_sub_sig* in = (zdotc_sub_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || 0) { return 0; }; return in; }
sdsdot_sig* chk_sdsdot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sdsdot_sig* in = (sdsdot_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dsdot_sig* chk_dsdot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsdot_sig* in = (dsdot_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
snrm2_sig* chk_snrm2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; snrm2_sig* in = (snrm2_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dnrm2_sig* chk_dnrm2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dnrm2_sig* in = (dnrm2_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
scnrm2_sig* chk_scnrm2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; scnrm2_sig* in = (scnrm2_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dznrm2_sig* chk_dznrm2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dznrm2_sig* in = (dznrm2_sig*)(x+1); if( in->lst.len != 2 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
srot_sig* chk_srot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; srot_sig* in = (srot_sig*)(x+1); if( in->lst.len != 5 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; }
drot_sig* chk_drot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; drot_sig* in = (drot_sig*)(x+1); if( in->lst.len != 5 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; }
csrot_sig* chk_csrot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; csrot_sig* in = (csrot_sig*)(x+1); if( in->lst.len != 5 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; }
zdrot_sig* chk_zdrot_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zdrot_sig* in = (zdrot_sig*)(x+1); if( in->lst.len != 5 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; }
/* srotg_sig* chk_srotg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; srotg_sig* in = (srotg_sig*)(x+1); if( in->lst.len != 4 || (ART(in->A.hdr) != 15) || (ART(in->B.hdr) != 15) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; } */
/* drotg_sig* chk_drotg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; drotg_sig* in = (drotg_sig*)(x+1); if( in->lst.len != 4 || (ART(in->A.hdr) != 15) || (ART(in->B.hdr) != 15) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; } */
/* crotg_sig* chk_crotg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; crotg_sig* in = (crotg_sig*)(x+1); if( in->lst.len != 4 || (ART(in->A.hdr) != 15) || (ART(in->B.hdr) != 15) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; } */
/* zrotg_sig* chk_zrotg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zrotg_sig* in = (zrotg_sig*)(x+1); if( in->lst.len != 4 || (ART(in->A.hdr) != 15) || (ART(in->B.hdr) != 15) || (ART(in->C.hdr) != 15) || (ART(in->S.hdr) != 15) || 0) { return 0; }; return in; } */
srotm_sig* chk_srotm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; srotm_sig* in = (srotm_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->P.hdr) != 15) || 0) { return 0; }; return in; }
drotm_sig* chk_drotm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; drotm_sig* in = (drotm_sig*)(x+1); if( in->lst.len != 4 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->P.hdr) != 15) || 0) { return 0; }; return in; }
/* srotmg_sig* chk_srotmg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; srotmg_sig* in = (srotmg_sig*)(x+1); if( in->lst.len != 5 || (ART(in->D1.hdr) != 15) || (ART(in->D2.hdr) != 15) || (ART(in->B1.hdr) != 15) || (ART(in->B2.hdr) != 15) || (ART(in->P.hdr) != 15) || 0) { return 0; }; return in; } */
/* drotmg_sig* chk_drotmg_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; drotmg_sig* in = (drotmg_sig*)(x+1); if( in->lst.len != 5 || (ART(in->D1.hdr) != 15) || (ART(in->D2.hdr) != 15) || (ART(in->B1.hdr) != 15) || (ART(in->B2.hdr) != 15) || (ART(in->P.hdr) != 15) || 0) { return 0; }; return in; } */
sscal_sig* chk_sscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sscal_sig* in = (sscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dscal_sig* chk_dscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dscal_sig* in = (dscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
cscal_sig* chk_cscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cscal_sig* in = (cscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
zscal_sig* chk_zscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zscal_sig* in = (zscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
csscal_sig* chk_csscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; csscal_sig* in = (csscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
zdscal_sig* chk_zdscal_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zdscal_sig* in = (zdscal_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
sswap_sig* chk_sswap_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sswap_sig* in = (sswap_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dswap_sig* chk_dswap_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dswap_sig* in = (dswap_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
cswap_sig* chk_cswap_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cswap_sig* in = (cswap_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zswap_sig* chk_zswap_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zswap_sig* in = (zswap_sig*)(x+1); if( in->lst.len != 3 || (in->typN != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sgemv_sig* chk_sgemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sgemv_sig* in = (sgemv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dgemv_sig* chk_dgemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dgemv_sig* in = (dgemv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
cgemv_sig* chk_cgemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cgemv_sig* in = (cgemv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zgemv_sig* chk_zgemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zgemv_sig* in = (zgemv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sgbmv_sig* chk_sgbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sgbmv_sig* in = (sgbmv_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (in->typKL != 13) || (in->typKU != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dgbmv_sig* chk_dgbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dgbmv_sig* in = (dgbmv_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (in->typKL != 13) || (in->typKU != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
cgbmv_sig* chk_cgbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cgbmv_sig* in = (cgbmv_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (in->typKL != 13) || (in->typKU != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zgbmv_sig* chk_zgbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zgbmv_sig* in = (zgbmv_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typM != 13) || (in->typN != 13) || (in->typKL != 13) || (in->typKU != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sger_sig* chk_sger_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sger_sig* in = (sger_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
dger_sig* chk_dger_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dger_sig* in = (dger_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
cgerc_sig* chk_cgerc_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cgerc_sig* in = (cgerc_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
zgerc_sig* chk_zgerc_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zgerc_sig* in = (zgerc_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
cgeru_sig* chk_cgeru_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cgeru_sig* in = (cgeru_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
zgeru_sig* chk_zgeru_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zgeru_sig* in = (zgeru_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
chbmv_sig* chk_chbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chbmv_sig* in = (chbmv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zhbmv_sig* chk_zhbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhbmv_sig* in = (zhbmv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
chemv_sig* chk_chemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chemv_sig* in = (chemv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zhemv_sig* chk_zhemv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhemv_sig* in = (zhemv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
cher_sig* chk_cher_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cher_sig* in = (cher_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
zher_sig* chk_zher_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zher_sig* in = (zher_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
cher2_sig* chk_cher2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cher2_sig* in = (cher2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
zher2_sig* chk_zher2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zher2_sig* in = (zher2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
chpmv_sig* chk_chpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chpmv_sig* in = (chpmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
zhpmv_sig* chk_zhpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhpmv_sig* in = (zhpmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
chpr_sig* chk_chpr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chpr_sig* in = (chpr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.hdr) != 15) || 0) { return 0; }; return in; }
zhpr_sig* chk_zhpr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhpr_sig* in = (zhpr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.hdr) != 15) || 0) { return 0; }; return in; }
chpr2_sig* chk_chpr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chpr2_sig* in = (chpr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->AP.hdr) != 15) || 0) { return 0; }; return in; }
zhpr2_sig* chk_zhpr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhpr2_sig* in = (zhpr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->AP.hdr) != 15) || 0) { return 0; }; return in; }
ssbmv_sig* chk_ssbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssbmv_sig* in = (ssbmv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dsbmv_sig* chk_dsbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsbmv_sig* in = (dsbmv_sig*)(x+1); if( in->lst.len != 9 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sspmv_sig* chk_sspmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sspmv_sig* in = (sspmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dspmv_sig* chk_dspmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dspmv_sig* in = (dspmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
sspr_sig* chk_sspr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sspr_sig* in = (sspr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->AP.hdr) != 15) || 0) { return 0; }; return in; }
dspr_sig* chk_dspr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dspr_sig* in = (dspr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->AP.hdr) != 15) || 0) { return 0; }; return in; }
sspr2_sig* chk_sspr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sspr2_sig* in = (sspr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.hdr) != 15) || 0) { return 0; }; return in; }
dspr2_sig* chk_dspr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dspr2_sig* in = (dspr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.hdr) != 15) || 0) { return 0; }; return in; }
ssymv_sig* chk_ssymv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssymv_sig* in = (ssymv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
dsymv_sig* chk_dsymv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsymv_sig* in = (dsymv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || 0) { return 0; }; return in; }
ssyr_sig* chk_ssyr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssyr_sig* in = (ssyr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
dsyr_sig* chk_dsyr_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsyr_sig* in = (dsyr_sig*)(x+1); if( in->lst.len != 6 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
ssyr2_sig* chk_ssyr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssyr2_sig* in = (ssyr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
dsyr2_sig* chk_dsyr2_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsyr2_sig* in = (dsyr2_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || (ART(in->Y.arr.hdr) != 8) || (in->Y.lst.len !=2) || (in->Y.typinc != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || 0) { return 0; }; return in; }
stbmv_sig* chk_stbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; stbmv_sig* in = (stbmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtbmv_sig* chk_dtbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtbmv_sig* in = (dtbmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctbmv_sig* chk_ctbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctbmv_sig* in = (ctbmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztbmv_sig* chk_ztbmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztbmv_sig* in = (ztbmv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
stbsv_sig* chk_stbsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; stbsv_sig* in = (stbsv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtbsv_sig* chk_dtbsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtbsv_sig* in = (dtbsv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctbsv_sig* chk_ctbsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctbsv_sig* in = (ctbsv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztbsv_sig* chk_ztbsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztbsv_sig* in = (ztbsv_sig*)(x+1); if( in->lst.len != 8 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
stpmv_sig* chk_stpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; stpmv_sig* in = (stpmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtpmv_sig* chk_dtpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtpmv_sig* in = (dtpmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctpmv_sig* chk_ctpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctpmv_sig* in = (ctpmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztpmv_sig* chk_ztpmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztpmv_sig* in = (ztpmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
stpsv_sig* chk_stpsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; stpsv_sig* in = (stpsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtpsv_sig* chk_dtpsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtpsv_sig* in = (dtpsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctpsv_sig* chk_ctpsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctpsv_sig* in = (ctpsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztpsv_sig* chk_ztpsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztpsv_sig* in = (ztpsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->AP.hdr) != 15) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
strmv_sig* chk_strmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; strmv_sig* in = (strmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtrmv_sig* chk_dtrmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtrmv_sig* in = (dtrmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctrmv_sig* chk_ctrmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctrmv_sig* in = (ctrmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztrmv_sig* chk_ztrmv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztrmv_sig* in = (ztrmv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
strsv_sig* chk_strsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; strsv_sig* in = (strsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
dtrsv_sig* chk_dtrsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtrsv_sig* in = (dtrsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ctrsv_sig* chk_ctrsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctrsv_sig* in = (ctrsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
ztrsv_sig* chk_ztrsv_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztrsv_sig* in = (ztrsv_sig*)(x+1); if( in->lst.len != 7 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typN != 13) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->X.arr.hdr) != 8) || (in->X.lst.len !=2) || (in->X.typinc != 13) || 0) { return 0; }; return in; }
sgemm_sig* chk_sgemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; sgemm_sig* in = (sgemm_sig*)(x+1); if( in->lst.len != 13 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typTRANSB != 13) || (in->typM != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
dgemm_sig* chk_dgemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dgemm_sig* in = (dgemm_sig*)(x+1); if( in->lst.len != 13 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typTRANSB != 13) || (in->typM != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
cgemm_sig* chk_cgemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cgemm_sig* in = (cgemm_sig*)(x+1); if( in->lst.len != 13 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typTRANSB != 13) || (in->typM != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zgemm_sig* chk_zgemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zgemm_sig* in = (zgemm_sig*)(x+1); if( in->lst.len != 13 || (in->typORDER != 13) || (in->typTRANSA != 13) || (in->typTRANSB != 13) || (in->typM != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
chemm_sig* chk_chemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; chemm_sig* in = (chemm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zhemm_sig* chk_zhemm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zhemm_sig* in = (zhemm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
cherk_sig* chk_cherk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cherk_sig* in = (cherk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zherk_sig* chk_zherk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zherk_sig* in = (zherk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
cher2k_sig* chk_cher2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; cher2k_sig* in = (cher2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zher2k_sig* chk_zher2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zher2k_sig* in = (zher2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
ssymm_sig* chk_ssymm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssymm_sig* in = (ssymm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
dsymm_sig* chk_dsymm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsymm_sig* in = (dsymm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
csymm_sig* chk_csymm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; csymm_sig* in = (csymm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zsymm_sig* chk_zsymm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zsymm_sig* in = (zsymm_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
ssyrk_sig* chk_ssyrk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssyrk_sig* in = (ssyrk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
dsyrk_sig* chk_dsyrk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsyrk_sig* in = (dsyrk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
csyrk_sig* chk_csyrk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; csyrk_sig* in = (csyrk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zsyrk_sig* chk_zsyrk_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zsyrk_sig* in = (zsyrk_sig*)(x+1); if( in->lst.len != 10 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
ssyr2k_sig* chk_ssyr2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ssyr2k_sig* in = (ssyr2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
dsyr2k_sig* chk_dsyr2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dsyr2k_sig* in = (dsyr2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
csyr2k_sig* chk_csyr2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; csyr2k_sig* in = (csyr2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
zsyr2k_sig* chk_zsyr2k_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; zsyr2k_sig* in = (zsyr2k_sig*)(x+1); if( in->lst.len != 12 || (in->typORDER != 13) || (in->typUPLO != 13) || (in->typTRANS != 13) || (in->typN != 13) || (in->typK != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || (ART(in->BETA.hdr) != 15) || (ART(in->C.arr.hdr) != 8) || (in->C.lst.len !=2) || (in->C.typlda != 13) || 0) { return 0; }; return in; }
strmm_sig* chk_strmm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; strmm_sig* in = (strmm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
dtrmm_sig* chk_dtrmm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtrmm_sig* in = (dtrmm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
ctrmm_sig* chk_ctrmm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctrmm_sig* in = (ctrmm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
ztrmm_sig* chk_ztrmm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztrmm_sig* in = (ztrmm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
strsm_sig* chk_strsm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; strsm_sig* in = (strsm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
dtrsm_sig* chk_dtrsm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; dtrsm_sig* in = (dtrsm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
ctrsm_sig* chk_ctrsm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ctrsm_sig* in = (ctrsm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }
ztrsm_sig* chk_ztrsm_sig(S x){ if (x[0] != 1 || x[1] != 1) return 0; ztrsm_sig* in = (ztrsm_sig*)(x+1); if( in->lst.len != 11 || (in->typORDER != 13) || (in->typSIDE != 13) || (in->typUPLO != 13) || (in->typTRANSA != 13) || (in->typDIAG != 13) || (in->typM != 13) || (in->typN != 13) || (ART(in->ALPHA.hdr) != 15) || (ART(in->A.arr.hdr) != 8) || (in->A.lst.len !=2) || (in->A.typlda != 13) || (ART(in->B.arr.hdr) != 8) || (in->B.lst.len !=2) || (in->B.typlda != 13) || 0) { return 0; }; return in; }

